/*! Copyright 2025 Adobe
All Rights Reserved. */
import"@dropins/tools/lib.js";import{events as U}from"@dropins/tools/event-bus.js";import{signal as y,computed as m}from"@dropins/tools/signals.js";import{FetchGraphQL as N}from"@dropins/tools/fetch-graphql.js";const S={authenticated:!1,cartId:null,initialized:!1,config:null},D=new Proxy(S,{set(e,t,s){return e[t]=s,!0},get(e,t){return e[t]}}),V=()=>D.config;class G extends Error{constructor(t){super(t.map(s=>s.message).join(" ")),this.name="FetchError"}}class w extends Error{constructor(t){super(t),this.name="InvalidInput"}}class a extends w{constructor(t){super(`${t} is required.`)}}class B extends a{constructor(){super("Cart ID")}}class $ extends Error{constructor(){super("User is not authenticated")}}class z extends a{constructor(){super("Negotiable Quote ID")}}class Y extends a{constructor(){super("Email")}}class J extends a{constructor(){super("Payment method code")}}class K extends a{constructor(){super("Shipping address")}}class W extends a{constructor(){super("Shipping method")}}class Z extends a{constructor(){super("Billing address")}}class ee extends a{constructor(){super("Country Code")}}var c=(e=>(e.EXCLUDING_TAX="EXCLUDING_TAX",e.INCLUDING_EXCLUDING_TAX="INCLUDING_AND_EXCLUDING_TAX",e.INCLUDING_TAX="INCLUDING_TAX",e))(c||{}),A=(e=>(e.CartUpdate="cartUpdate",e.QuoteUpdates="quoteUpdates",e.Default="default",e.ShippingEstimate="shippingEstimate",e))(A||{});const d=new Map,g=new Map,u=y(new Set),E=new Map;E.set("cartUpdate",e=>{U.emit("checkout/updated",e)});async function X(e){g.set(e,!0);const t=d.get(e);let s;for(;t.length>0;){const i=t.shift();try{const n=await i.requestFn();i.resolve(n),s=n}catch(n){i.reject(n)}}g.set(e,!1);const r=new Set(u.value);r.delete(e),u.value=r;const o=E.get(e);o&&s&&o(s)}function q(e,t="default"){d.has(t)||d.set(t,[]);const s=d.get(t),r=new Promise((i,n)=>{s.push({requestFn:e,resolve:i,reject:n})}),o=new Set(u.value);return o.add(t),u.value=o,g.get(t)||X(t),r}const te=m(()=>u.value.has("cartUpdate")),se=m(()=>u.value.has("shippingEstimate")),v=["sender_email","recipient_email"];function T(e){return e.filter(t=>!t.path||!v.some(s=>{var r;return((r=t.path)==null?void 0:r.at(-1))===s}))}function L(e,t){return t.split(".").reduce((s,r)=>s&&s[r]!==void 0?s[r]:void 0,e)}async function M(e){const{defaultValueOnFail:t,options:s,path:r,query:o,queueName:i,transformer:n,type:p}=e;try{const l=async()=>{const{data:I,errors:_}=await Q(o,{method:p==="query"?"GET":"POST",cache:p==="query"?"no-cache":void 0,...s});if(_){const C=T(_);if(C.length>0)throw new G(C)}let h=L(I,r);if(h===void 0)throw new Error(`No data found at path: ${r}`);return n?n(h):h};return p==="mutation"?await q(l,i):await l()}catch(l){if(t!==void 0)return t;throw l}}const x=`
  query getStoreConfig {
    storeConfig {
      default_country
      is_checkout_agreements_enabled
      is_guest_checkout_enabled
      is_one_page_checkout_enabled
      shopping_cart_display_shipping
    }
  }
`,F="US",f={defaultCountry:F,agreementsEnabled:!0,shoppingCartDisplaySetting:{shipping:c.EXCLUDING_TAX}},re=async()=>await M({defaultValueOnFail:f,options:{method:"GET",cache:"no-cache"},path:"storeConfig",query:x,transformer:P,type:"query"});function b(e){switch(e){case 1:return c.EXCLUDING_TAX;case 2:return c.INCLUDING_TAX;case 3:return c.INCLUDING_EXCLUDING_TAX;default:return c.EXCLUDING_TAX}}function P(e){if(!e)return f;const{default_country:t,is_checkout_agreements_enabled:s,shopping_cart_display_shipping:r}=e;return{defaultCountry:t||f.defaultCountry,agreementsEnabled:s,shoppingCartDisplaySetting:{shipping:b(r)}}}const{setEndpoint:ne,setFetchGraphQlHeader:ae,removeFetchGraphQlHeader:oe,setFetchGraphQlHeaders:ie,fetchGraphQl:Q,getConfig:ce}=new N().getMethods();export{F as D,w as I,B as M,A as Q,f as S,c as T,$ as U,se as a,ee as b,z as c,M as d,a as e,K as f,W as g,te as h,V as i,ne as j,ae as k,ie as l,Q as m,ce as n,re as o,J as p,Y as q,oe as r,D as s,Z as t};
//# sourceMappingURL=fetch-graphql.js.map
