/*! Copyright 2025 Adobe
All Rights Reserved. */
import{s as n,M as g,d as y,o as d}from"./fetch-graphql.js";import{merge as v,Initializer as C}from"@dropins/tools/lib.js";import{events as o}from"@dropins/tools/event-bus.js";import{CHECKOUT_DATA_FRAGMENT as c}from"../fragments.js";const x=async(e=!1)=>{n.authenticated=e},A=e=>{if(e)return{code:e.code,title:e.title}},b=e=>{if(e)return e.filter(t=>!!t).map(t=>{const{code:i,title:r}=t;return{code:i,title:r}})},I=e=>e?"code"in e&&"value"in e:!1,M=e=>e.filter(I).map(t=>{const{code:i,value:r}=t;return{code:i,value:r}}),l=e=>{const t=e.street.filter(Boolean);return{id:(e==null?void 0:e.id)||void 0,city:e.city,company:e.company||void 0,country:N(e.country),customAttributes:M(e.custom_attributes),firstName:e.firstname,lastName:e.lastname,postCode:e.postcode||void 0,region:z(e.region),street:t,telephone:e.telephone||void 0,vatId:e.vat_id||void 0,prefix:e.prefix||void 0,suffix:e.suffix||void 0,middleName:e.middlename||void 0,fax:e.fax||void 0}},T=e=>{if(e)return l(e)},S=e=>e.filter(t=>!!t).map(t=>{const{available_shipping_methods:i,selected_shipping_method:r,same_as_billing:s,...h}=t;return{...l(h),availableShippingMethods:$(i),selectedShippingMethod:P(r),sameAsBilling:s}}),U=e=>({city:e.city,company:e.company,country_code:e.countryCode,custom_attributes:e.customAttributes.map(t=>({attribute_code:t.code,value:t.value})),firstname:e.firstName,lastname:e.lastName,postcode:e.postcode,region:e.region,region_id:e.regionId,save_in_address_book:e.saveInAddressBook??!0,street:e.street,telephone:e.telephone,vat_id:e.vatId,prefix:e.prefix,suffix:e.suffix,middlename:e.middleName,fax:e.fax}),k=e=>{var i,r,s;if(!e)return;const t={availablePaymentMethods:b(e.available_payment_methods),billingAddress:T(e.billing_address),email:e.email??void 0,id:e.id,isEmpty:e.total_quantity===0,isVirtual:e.is_virtual,selectedPaymentMethod:A(e.selected_payment_method),shippingAddresses:S(e.shipping_addresses),isGuest:!n.authenticated};return v(t,(s=(r=(i=G.getConfig().models)==null?void 0:i.CartModel)==null?void 0:r.transformer)==null?void 0:s.call(r,e))},N=e=>({code:(e==null?void 0:e.code)??"",label:(e==null?void 0:e.label)??""}),z=e=>{if(!(!(e!=null&&e.code)||!(e!=null&&e.label)))return{code:e.code,name:e.label,id:e.region_id??void 0}},E=(e,t)=>e.amount.value-t.amount.value,w=e=>e==null,u=e=>!(!e||!e.method_code||!e.method_title||w(e.amount.value)||!e.amount.currency),m=e=>({amount:{value:e.amount.value,currency:e.amount.currency},title:e.method_title,code:e.method_code,carrier:{code:e.carrier_code,title:e.carrier_title},value:`${e.carrier_code} - ${e.method_code}`,...e.price_excl_tax&&{amountExclTax:{value:e.price_excl_tax.value,currency:e.price_excl_tax.currency}},...e.price_incl_tax&&{amountInclTax:{value:e.price_incl_tax.value,currency:e.price_incl_tax.currency}}}),P=e=>{if(u(e))return m(e)},$=e=>e?e.filter(u).map(t=>m(t)).sort(E):[],q=`
  query getCart($cartId: String!) {
    cart(cart_id: $cartId) {
      ...CHECKOUT_DATA_FRAGMENT
    }
  }

  ${c}
`,B=`
  query getCustomerCart {
    cart: customerCart {
      ...CHECKOUT_DATA_FRAGMENT
    }
  }

  ${c}
`,a=async()=>{const e=n.cartId,t=n.authenticated===!1,i=t?q:B,r=t?{cartId:e}:{};if(t&&!e)throw new g;return await y({type:"query",query:i,options:{method:"POST",cache:"no-cache",variables:r},path:"cart",transformer:k})},D=()=>[o.on("authenticated",x,{eager:!0}),o.on("cart/initialized",p,{eager:!0}),o.on("cart/reset",O),o.on("cart/updated",_)],f=new C({init:async e=>{const t={...e};f.config.setConfig(t)},listeners:D}),G=f.config,p=async e=>{if(n.initialized)return _(e);n.config||(n.config=await d());const t=e?e.id:null;n.cartId=t;const i=t?await a():null;n.initialized=!0,o.emit("checkout/initialized",i||null)},O=()=>{n.cartId=null,o.emit("checkout/updated",null)},_=async e=>{if(!n.initialized)return p(e);const t=e?e.id:null;n.cartId=t;const i=t?await a():null;o.emit("checkout/updated",i||null)};export{$ as a,z as b,G as c,N as d,A as e,b as f,U as g,k as h,x as i,a as j,f as k,p as l,O as r,_ as s,P as t};
//# sourceMappingURL=synchronizeCheckout.js.map
